filter:
  excluded_paths:
    - 'server/coverage/*'

checks:
  javascript: true
build:
  image: default-bionic

  nodes:
    my-tests:
      environment:
        node:
          version: '18.x'
    analysis:
      tests:
        override:
          - command: 'js-scrutinizer-run'
    tests: true
  tests:
    environment:
      node:
        version: '18.x'
    override:
    - command: 'cd server && npm install && npm rebuild && npm run testCoverage'
      coverage:
        file: 'server/coverage/clover.xml'
        format: 'clover'
