filter:
  excluded_paths:
    - 'server/coverage/*'

checks:
  javascript: true
build:
  image: default-bionic
  environment:
    node: '18.x'

  nodes:
    my-tests:
      tests:
        override:
          - command: 'cd server && npm install && npm rebuild && npm run testCoverage'
            coverage:
              file: 'server/coverage/clover.xml'
              format: 'clover'
    analysis:
      tests:
        override:
          - command: 'js-scrutinizer-run'
    tests: true
