filter:
  excluded_paths:
    - 'server/coverage/*'

build:
  nodes:
    analysis:
      tests:
        override:
          -
            command: 'cd server && npm install && npm rebuild && npm run testCoverage'
            coverage:
              file: 'server/coverage/clover.xml'
              format: 'clover'
      environment:
        node:
          version: "16.20.2"