filter:
  excluded_paths:
    - 'server/coverage/*'

build:
  nodes:
    my-tests:
      environment:
        node:
          version: 16.20.2
    analysis:
      tests:
        override:
          js-scrutinizer-run:
  tests:
    commands:
        command: 'cd server && npm install && npm rebuild && npm run testCoverage'
    coverage:
      file: 'server/coverage/clover.xml'
      format: 'clover'
