filter:
  excluded_paths:
    - 'server/coverage/*'

build:
  nodes:
    analysis:
      tests:
        js-scrutinizer-run:
          override:
            - 'cd server && npm install && npm rebuild && npm run testCoverage'
          environment:
            node:
              version: "16.20.2"
          coverage:
            file: 'server/coverage/clover.xml'
            format: 'clover'
    # tests:
    #   commands:
    #     - name: 'Run Unit Tests'
    #       command: 'cd server && npm install && npm rebuild && npm run testCoverage'
    #   environment:
    #     node:
    #       version: "16.20.2"
    #   coverage:
    #     file: 'server/coverage/clover.xml'
    #     format: 'clover'

