version: "3"
networks:
    dbwebb:
volumes:
  data:
services:
    # client:
    #     build: ./client
    #     # image: "sp4ngberg/elsparkcyklar-client:1.0"
    #     volumes:
    #     - ./client:/client
    #     container_name: elsparkcyklarclient
    #     ports:
    #       - "3000:3000"
    #     networks:
    #       dbwebb:
    #     restart:
    #       "always"
    # webbapp:
    #     build: ./webbapp
    #     # image: "sp4ngberg/elsparkcyklar-webbapp:1.0"
    #     volumes:
    #     - ./webbapp:/webbapp
    #     container_name: elsparkcyklarwebbapp
    #     ports:
    #       - "3001:3001"
    #     networks:
    #       dbwebb:
    #     restart:
    #       "always"
    database:
      image: mongo
      restart: always
      ports:
        - "27018:27017"
      environment:
        MONGO_INITDB_DATABASE: vteam
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: secret
      volumes:
        - ./data/db2:/data/db
      networks:
        dbwebb:
    server:
        build: ./server
        # image: "sp4ngberg/elsparkcyklar-server:1.0"
        volumes:
          - ./data:/server/data
          - ./server:/server
        container_name: elsparkcyklarserver
        ports:
          - "1337:1337"
        networks:
          dbwebb:
        restart:
          "always"
