# version: "3"
# networks:
#     dbwebb:
# volumes:
#   data:
# services:
#     server:
#         image: "sp4ngberg/elsparkcyklar-server:1.0"
#         volumes:
#           - ./data:/server/data
#         container_name: elsparkcyklarserver
#         ports:
#           - "1337:1337"
#         networks:
#           dbwebb:
#         restart:
#           "always"
#     client:
#         image: "sp4ngberg/elsparkcyklar-client:1.0"
#         container_name: elsparkcyklarclient
#         ports:
#           - "3000:3000"
#         restart:
#           "always"

version: '3.1'
services:
  mongo:
    image: mongo
    volumes:
      - ./data/db:/data/db
    ports:
      - 27018:27017