version: "3"
networks:
    dbwebb:
volumes:
  data:
services:
    server:
        image: "sp4ngberg/elsparkcyklar-server:1.0"
        volumes:
          - ./data:/server/data
        container_name: elsparkcyklarserver
        ports:
          - "1337:1337"
        networks:
          dbwebb:
        restart:
          "always"
    client:
        image: "sp4ngberg/elsparkcyklar-client:1.0"
        container_name: elsparkcyklarclient
        ports:
          - "3000:3000"
        networks:
          dbwebb:
        restart:
          "always"
    webbapp:
        image: "sp4ngberg/elsparkcyklar-webbapp:1.0"
        container_name: elsparkcyklarwebbapp
        ports:
          - "3001:3001"
        networks:
          dbwebb:
        restart:
          "always"
    database:
      image: mongo
      restart: always
      ports:
        - "27017:27017"
      environment:
        MONGO_INITDB_DATABASE: vteam
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: secret
      volumes:
        - data:/data/db
      networks:
        dbwebb:
