name: Build and publish Docker Image CI

on:
  push:
    branches:
      - main
  pull_request_target:
    branches:
      - main

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Pack Remote Build
        uses: dfreilich/pack-action@v2.1.1
        with:
          args: 'build elsparkcyklar-server:1.0 --builder sp4ngberg --publish'
      - name: Test App
        run: |
          docker run -d -p 1337:13337 --name personal-portfolio elsparkcyklar-server
          sleep 30s
          curl --request GET --url http://localhost:1337
