name: Build and publish Docker Image CI

on:
  push:
    branches:
      - main
  pull_request_target:
    branches:
      - main

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build & Push Image Backend
        run: |
          cd server/
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_SERVER_IMAGE }}:1.0 .
          docker image ls
          docker image push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_SERVER_IMAGE }}:1.0
      - name: Build & Push Image Webb-site
        run: |
          cd client/
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_CLIENT_IMAGE }}:1.0 .
          docker image ls
          docker image push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_CLIENT_IMAGE }}:1.0
      - name: Build & Push Image Webb-app
        run: |
          cd webbapp/
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_WEBBAPP_IMAGE }}:1.0 .
          docker image ls
          docker image push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_WEBBAPP_IMAGE }}:1.0
