name: Build and publish Docker Image CI

on:
  push:
    branches:
      - main
  pull_request_target:
    branches:
      - main

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build & Push repo to image
        run: |
          cd server/
          docker build -t sp4ngberg/elsparkcyklar-server:1.0 .
          docker image ls
          docker image push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE }}:1.0

